### ISSUE TITLE
Create a Vue single-file component for the hamburger icon

### ISSUE THREAD

**Issue by kevreth** [kevreth/CyberLearning#17]
As a Vue starter exercise, make the hamburger icon a single-file component. The filename will be "hamburger.vue".
Install the Vue add-in for Visual Studio Code to make work easier.

This will probably require adding a Gulp plugin to compile Vue source files.

**Comment by sashacode11** [comment]
the hamburger icon single-file component didn't work when I import a hamburgericon.vue to a main.ts file, I tried to delete the code exist but it still not work

**Comment by kevreth** [comment]
This is partially finished. The Vue raster hamburger icon appears on all pages now so we know Vue works. To complete this task, replace the raster icon with the SVG icon. The SVG icon should be placed with CSS, not in with manipulating the SVG itself.
