### ISSUE TITLE
Implement QHierarchy on overlay

### ISSUE THREAD

**Issue by kevreth** [kevreth/CyberLearning#95]
Implement QHierachy on the overlay using default data as seen here:

https://next-quasar-qhierarchy.netlify.app/example-qhierarchy-default-expand-all

Also the example at

https://quasar-qhierarchy.netlify.app/examples

Under "Default Expand All" shows both the template and script sections that can probably be copied and pasted.

It should support a vertical scrollbar and provide a way to initialize the data programmatically.

The QHierarchy should be centered on the overlay. Replace the "start over" button content with a Quasar material design trash can icon and move it to the left of the close button.

Implement in a new component, ProgressTable.vue.

RESOURCES:
https://next-quasar-qhierarchy.netlify.app/
https://quasar-qhierarchy.netlify.app/examples
https://github.com/pratik227/quasar-qhierarchy

**Comment by sashacode11** [comment]
Waiting to find out how to do this: "Under "Default Expand All" shows both the template and script sections that can probably be copied and pasted."

**Comment by kevreth** [comment]
> Waiting to find out how to do this: "Under "Default Expand All" shows both the template and script sections that can probably be copied and pasted."

That's referring to what is shown on this page: https://quasar-qhierarchy.netlify.app/examples

It's not a requirement for you to implement.
